version: '3.3                                                                               '

services:
  memcached-fast-api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - memcached
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"