version: "3.8"
services:
  hazelcast-fast-api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - hazelcast
  hazelcast:
    image: hazelcast/hazelcast:5.0
    ports:
    - "5701:5701"
  management-center:
    image: hazelcast/management-center:5.4.1
    ports:
    - "8080:8080"
    environment:
    - MC_DEFAULT_CLUSTER=dev
    - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast