version: "3"
services:
  ignite-fast-api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      ignite:
        condition: service_healthy
    environment:
      - IGNITE_HOST=ignite
      - IGNITE_PORT=10800
  
  ignite:
    image: 'apacheignite/ignite:latest'
    ports:
      - '10800:10800'
    environment:
      - CONFIG_URI=/config-file.xml
      - IGNITE_WORK_DIR=/storage
    volumes:
      - type: bind
        source: ./config-file.xml
        target: /config-file.xml
      - ./storage:/storage:rw
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "10800"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 40s